### ISSUE TITLE
Use ABIEncoderV2 to work around 'stack too deep' issues

### ISSUE THREAD

**Issue by nventuro** [opengsn/gsn#155]
`relayCall` and `recipientCallsAtomic` are hard to make changes to because they have too many local variables stored in the stack, causing the compiler to emit 'stack too deep' errors. This is particularly problematic because we actually need to have these functions hold _more_ variables, since some required values are not currently being forwarded, and we still need to rework the charge calculations, which will take some extra slots.

A clean and maintainable way to do achieve this is storing `relayCall`'s arguments in a `struct`, which are kept in `memory`. However, since `recipientCallsAtomic` is an `external` function, we need to enable the ABIEncoderV2 (an experimental feature) for this to work. This may raise concerns from a security point of view, since this encoder hasn't been as tested as the default one (though our use case is quite straightforward and doesn't require any of its tricky bits).

Additionally, it is likely that usage of the new encoder would bleed over into `IRelayRecipient`, which means that developers writing contracts that are GSN-callable will get the following warning when compiling their code:

```
Warning: Experimental features are turned on. Do not use experimental features on live deployments.
pragma experimental ABIEncoderV2;
^-------------------------------^
```

Are we ok with doing such a thing? I think this is a very reasonable course of action (and the only one I can think of), and fine for an MVP, but wanted to get thoughts and ideas around this.

**Comment by drortirosh** [comment]
I think we should avoid it in the interface. Notice that  the "atomic" is technically external but actually for internal use only.

I also thought of having all parameters passed as a single struct, using typed format like EIP712

**Comment by nventuro** [comment]
Regarding security, Chris (lead developer of the Solidity compiler) said this about our use case:

>I might say that by now, ABIEncoderV2 should be stable enough for "regular" uses. Due to its design, bugs should be detectable through simple tests and I would be surprised if there are still bugs that require certain data to trigger them.
This is especially true if you only use full-width types
