### ISSUE TITLE
relayUrl manual setting is broken

### ISSUE THREAD

**Issue by pertsev** [opengsn/gsn#233]
According to the [comments](https://github.com/tabookey/tabookey-gasless/blob/master/src/js/relayclient/RelayClient.js#L58) `relayUrl` option can be passed to constructor to "avoid lookup on relayHub for relays, and always use this URL/address". But it's not.

Please, have a look at this [PR](https://github.com/OpenZeppelin/openzeppelin-gsn-provider/pull/39)

**Comment by drortirosh** [comment]
actually, the "manual" entries for relay are obsolete. They were used during development, until we ironed out the registration and finding process.
Still you can always use `calculateRelayScore` to modify the priority of a given relay (or filter out)

**Comment by forshtat** [comment]
Fixed for GSNv2 https://github.com/opengsn/gsn/pull/329
