### ISSUE TITLE
Gauging general interest in a severless relay?

### ISSUE THREAD

**Issue by edukaded** [opengsn/gsn#237]
I am just testing the waters here to see if there is any interest in a serverless version of the relay.
First off, I would rather contribute than duplicate efforts, so is anyone working on anything like that?  If so I would love to pitch in, just need to know where.  
It seems like a natural fit and could be used to aide decentralization.

Furthermore can anyone think of a reason why the relay couldn't be deployed to a serverless environment such as lambda?

I mean there is of course the possibility of being DDoS'd, but putting the relay behind cloudflare would probably ease that quite a bit.

Thanx!

**Comment by drortirosh** [comment]
Actually, we think serverless (aws lambda/google functions) are a great fit for a relay. Any contribution would be appreciated !
current relay code is "cloud agnostic" (though our installation instructions are currently AWS specific) 
When making a serverless relay, one should bare in mind that serverless try to scale automatically - something that should be explicitly avoided with a relay - since a relay has a single private key (and nonce), and all requests should be serialized.
Also, the relay need some platform-specific way to keep its private key private (e.g KMS - though we didn't explore this)

**Comment by edukaded** [comment]
I've been evaluating the relay server code in depth and it seems there is a way to make a serverless version, but it's going to require a refactor in order to enable it.  

The primary issue here is going to be converting it from a stateful monolith to a stateless set of microservices.

Fortunately as far as I can tell there is nothing that requires using a monolith and the code base is small enough that the state can be factored out.  For instance instead of in memory cache, caching the information into a DB.  From there it's just a matter of using cloudwatch or similar to periodically trigger the timed functions that are presently managed by the monolith, things such as registering the relay each day and resuming stalled transactions.  

The hardest part will probably be trying to get these stateless endpoints to complete their tasks in the time restrictions of something like lambda.  It's possible some aspects will need to be pipelined into a task queue.

I've done this before.  www.tqnext.com is a shapeshift & changelly competitor we've developed and are in the process of launching that facilitates anonymous crypto trading.  It is comprised of a static content website overlaying some ajax which is calling into a backend comprised of 6 API endpoints each of which is it's own standalone microservice (lambda function) sitting at api.tqnext.com  Thus far it's performing beautifully even if the UI gets a bit clunky.  

However the roadmap for tqnext involves direct atomic onchain trading and that was one of the reasons GSN piqued my interest so much.  Being able to call contract functions such as deposit, withdrawal, bid / offer, match and trade without requiring the user to pay for gas is a huge competitive advantage for a DEX.

Managing keys is as you say a bit tricky.  My recommendation is to use S3 to store the key (encrypted) and pass in the password as an environment var.  But KMS is also an option, I just don't trust AWS (or any cloud provider for that matter) to keep such things truly secret.
