### ISSUE TITLE
Feature Request (nice to have) Reporting!

### ISSUE THREAD

**Issue by edukaded** [opengsn/gsn#239]
I just want to put out there that it would be nice to some sort of maybe optional reporting in the relayservers.  A daily summary would be nice.  Even better if it emailed me, by dropping it to the local email on the server.  Even just having a "getstats" call on the webinterface would be better than nothing.  

Right now I have no way to know if there have been any errors other than jumping on etherscan and looking for transactions involving my node.

I may look into doing exactly this if it isn't already a planned feature.  If I did would you accept a PR?

**Comment by drortirosh** [comment]
I agree some reporting tools are due, but I'm not sure they all should be in the relayserver itself.
e.g: an external tool can monitor the logs, and report on transactions of all or specific group of relays.
There are "local cases" that doesn't get on-chain (most obvious one is out-of-funds), and for that I thought of adding a webhook so a relay can send a message to its owner (e.g. slack) when the relay detects a local problem
