### ISSUE TITLE
Upgrade options for RelayHub

### ISSUE THREAD

**Issue by spalladino** [opengsn/gsn#245]
Given a possible upgrade to the RelayHub is required, I'm opening this issue to discuss ideas around what are the options for making upgrades simpler. The easiest option is to just deploy a new RelayHub version, spin up some relayers for it, and start phasing out the relayers on the old hub, while users update (both in their contracts and client-side code) the hub address.

Nevertheless, there may be other options that require less disruption for the users. However, they do require an admin account for the hub, which could be a multisig managed by alliance members.

1. Turning constants (such as minimum stake or delays) into parameters that can be tweaked without needing a new deployment. This would also allow them to be changed across networks (especially since 1 ETH on mainnet and 1 Dai on xDai may be really different!).

2- Splitting the hub logic into multiple contracts, as modules, that can be changed independently of the main hub. This would allow us to, for example, swap the penalization logic for a different one without having to change the hub address.

3- Keep a "hub of hubs" that lists the latest version of the RelayHub to use, as a means to signal clients what is the latest version to work with.

4- Make the relay hub fully upgradeable (using a delegate proxy pattern or similar) for a period of time, until we are comfortable enough to freeze the protocol.

**Comment by drortirosh** [comment]
All these upgrade options are nice, but share one drawback: You have to trust the owner (or multisig aliance)
Currently, as a dapp owner, you only trust the actual code. 

**The "trustless upgrade" as we saw it is:**
- Assume a bugfix update (no API change):
- A new RelayHub is created, and the alliance announce the fix (and maybe audit report)
- A new hub is deployed, with some relays.
- Each dApp owner, at its own time, evaluate the change, and switch its dapp to the new hub.
- **No client change**: Clients always query a dapp to determine the hub to use
   (a client that uses multiple GNS-enabled contract might go through 2 different hubs!)
- Gradually, all relay owners move their relays to the new hub (and unstake the ones on the old hub)
