### ISSUE TITLE
Consider storing relayer URL on storage instead of events

### ISSUE THREAD

**Issue by spalladino** [opengsn/gsn#246]
Given that we are constantly emitting relayer registration events as a keepalive, it may make sense to make events smaller (and thus cheaper) and move part of the data published (such as URL) to storage. We should calculate which is the turning point for storage vs event data, based on the number of times the event is emitted.

**Comment by shahafn** [comment]
We initially had it as storage, but decided against it. Maybe worth rethinking it, as the more frequently we emit the url, the better it would be to just use storage.
