### ISSUE TITLE
List of RelayHub improvements

### ISSUE THREAD

**Issue by spalladino** [opengsn/gsn#247]
Based on the work by @nventuro [here](https://github.com/OpenZeppelin/openzeppelin-gsn-provider/issues/40), I'm creating this issue to list all pending changes to the RelayHub, based on different conversations and issues that have been coming up. 

Unfortunately, we don't have the bandwidth to tackle these changes on our end at the moment, but we wanted to share them here so they can be looked into before a next version of the Hub is deployed. In particular, (3) is blocking some devs from integrating with the GSN, and there is a chance that EIP1884 may make matters worse.

1. Upgrade options for the RelayHub, such as making parameters configurable, using a module plug-in approach, delegating proxies, or even a registry of hubs (https://github.com/tabookey/tabookey-gasless/issues/245).

2. Rethink events used for relayer registration, both to reduce costs and to prevent DDoS attacks (see https://github.com/tabookey/tabookey-gasless/issues/179, https://github.com/tabookey/tabookey-gasless/issues/246).

3. Rework gas limits, to accommodate for use cases that require larger calldata (such as processing merkle proofs) or more gas for the postRelayedCall (such as https://github.com/tabookey/tabookey-gasless/issues/234), especially considering the SLOAD repricing from EIP1884 (see [here](https://gist.github.com/ritzdorf/1c6bd72955391e831f8a397d3152b4e0#relayhub)).

**Comment by rstormsf** [comment]
3. Rework gas limits. Make it configurable for contract owners. In case of tornado.cash, we would need to set custom limits for `post` and `accept` relay calls

**Comment by forshtat** [comment]
Better late then never

1. GSNv2 separate RelayHub and StakeManager, allowing multiple RelayHubs with different parameters to operate within the GSN. Relays don't need to have a stake on every RelayHub. I believe this solves the https://github.com/opengsn/gsn/issues/245

2.  #179, #246 are no longer relevant as register events are only emitted once.

3. https://github.com/opengsn/gsn/pull/283 allows custom gas limits for `accept-`, `pre-` and `post-`
