### ISSUE TITLE
PostRelayedCall Gas Calculation

### ISSUE THREAD

**Issue by drortirosh** [opengsn/gsn#253]
the purpose of `postRelayedCall` is to calculate the actual used gas by this transaction - the amount that will eventually be withdrawn from it and passed to the relay.
By calculating this value, it should be able to use its own logic to "delegate" this payment to its client. 
(e.g: charge the caller with tokens, and exchange them for this amount of eth)

### The problem: 
Currently, its very hard for `postRelayedCall` to perform this calculation. the `actualCharge` parameter is very mis-guiding: its not *actual* - its the actual charge plus max postRelayedCall charge.

Note that the actualCharge should include the cost of the `postRelayedCall` itself, which of course can't be calculated on chain.

### Required change:
At the minimum, we need to improve the documantation: better documentation of the `actualCharge` param (or renaming it...), and also document how to write such `postRelayedCall` to calculate the "real" actual charge (might need to add tests for that, as we did to calculate the `gasOverhead`)
If needed, the API should change.
@tabookey/dev , @nventuro

**Comment by forshtat** [comment]
While 'postRelayCall' gas work is not yet complete, the 'actual charge' variable was renamed 'gasUseWithoutPost'. It is denominated in 'gas', not 'wei', and does not include assumptions on 'postRelayedCall' gas usage.
