### ISSUE TITLE
RefreshGasPrice formula can lead to 0 MinGasPrice

### ISSUE THREAD

**Issue by forshtat** [opengsn/gsn#264]
Which, in turn, means the relay will be stuck not ready. Probably only an issue when running ganache with "-g 1" or possibly on other special case networks.

**Comment by drortirosh** [comment]
yes, we use float calculation, and `-g 1`  is below the precision of float.
use `-g 1e8` (0.1 gwei) for a "very low gas"...

**Comment by alex-forshtat-tbk** [comment]
@drortirosh I got it now. The issue to handle here for me is that the RelayClient eats up the error message and just says "No relay responded", which is bad for debugging.
