### ISSUE TITLE
Does GSN require constantinople hardfork?

### ISSUE THREAD

**Issue by EnchanterIO** [opengsn/gsn#274]
Hi,

I am trying to deploy the RelayHub but I am running into an out-of-gas error on a blockchain network without having Constantinople hardfork enabled, regardless how much gas I send with the TX: 

```
Error: Error: StatusError: Transaction: 0xbd0f92cf137d45f8e0085296a8321739f0dc3b6fc7a914decff312560f31926a exited with an error (status 0) after consuming all gas.
```

The moment I switch to a network with Constantinople hardwork enabled, I am able to deploy it even though it consumes 6M gas:

<img width="793" alt="Screen Shot 2020-01-23 at 15 57 14" src="https://user-images.githubusercontent.com/3595242/73002135-d48c2600-3e03-11ea-958c-362c99091baa.png">

Could you please confirm that the Constantinople bytecode improvements are a prerequisite?

PS: Nice rebranding to openeth-dev/gsn

**Comment by shahafn** [comment]
Constantinople isn't supposed to be required, can you provide more info on the tx/what you're trying to do?

**Comment by EnchanterIO** [comment]
I am running the migration from this repo to deploy a new RelayHub.
