### ISSUE TITLE
Decommissioning: Unstake, refund, shut down?

### ISSUE THREAD

**Issue by edukaded** [opengsn/gsn#275]
Ok perhaps I'm just stupid, but try as I might I can't figure out what I need to do in order to unstake my relaynode and shut it down.  This is nothing personal but my node has been running on mainnet since October.  In that time I see that we have paid gas for a dozen or more transactions and as far as I can tell, nothing was ever paid to my node despite always broadcasting a 10% fee.  Evidently something is configured incorrectly and at this point I just want to shut it down and repurpose the server for other things.  Before I do so, I need to get my stake off the hub and my funds out of the relay.

Can I get some step by step instructions on what I will need to do here?
Thanks!

**Comment by edukaded** [comment]
Ok so I think I figured this out, I'll put up a step by step guide once I verify I've got all the steps right.

**Comment by edukaded** [comment]
The first step is to use 
https://etherscan.io/address/0xd216153c06e857cd7f72665e0af1d7d82172f494#readContract
To check and see if your node can unstake.
At present mine says false, so I've shut off my relay node and will wait a day.

**Comment by shahafn** [comment]
Hey @edukaded thank you for your effort using the project. We are currently working on making it more approachable to developers so hopefully some of your issues regarding trying to figure out how to use it will be solved very soon.
To answer the initial question, the correct way to shut down a relay is first remove relay by calling `removeRelayByOwner(<relayAddress>)`,  waiting its delay period and then performing `unstake(<relayAddress>)`. Regardless, as the relay owner you can withdraw its balance from the hub anytime, and after removing relay you'd probably want to send its balance to your account as well by a normal  transfer tx.

**Comment by drortirosh** [comment]
Indeed, we should document it better.
Currently, you have to:
1. open https://etherscan.io/address/0xd216153c06e857cd7f72665e0af1d7d82172f494#writeContract
from the relay's owner account, and call `removeRelayByOwner
2. Wait for the unstake delay (the minimum is 1 week. )
3. Once the delay is over, you can use `unstake` method from the above page.
4. Keep the relay active all that time: once the relay sees it was unstaked, it will automatically send the remaining funds to the owner's account.
5. after that, you can safely de-commision the relay's host.
