### ISSUE TITLE
Public relayer CORS proxy problem

### ISSUE THREAD

**Issue by k06a** [opengsn/gsn#288]
```
new Web3(new GSNProvider('https://kovan-01.gsn.openzeppelin.org'))
```
>Access to XMLHttpRequest at 'https://kovan-01.gsn.openzeppelin.org/' from origin 'http://localhost:8101' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Related to the discussion: https://forum.openzeppelin.com/t/why-do-public-gsn-relayers-have-cors-limitations/2412

**Comment by drortirosh** [comment]
as per the request on the openzeppelin forum, please provide more info. we're unable to reproduce the issue. samples running on localhost have no problem accessing the public relates.
