### ISSUE TITLE
Could not receive RelayAdded() events for our relay

### ISSUE THREAD

**Issue by crossoveranx** [opengsn/gsn#303]
Our relay is emitting these logs for the past week or so, however beforehand for about a month it worked fine. I updated our relay to the GSNv1 located in the release after receiving these events but it keeps occurring. 

The strange thing is that it switches constantly between the Relay Ready status being Set to True and False, of course when it is set to True, these events are no longer emitted? This can be seen at https://relay.bloxberg.org/getaddr

Any suggestions on what to try to fix the problem and to make the relay stable again? Our network is running PoA on Ethereum on the Istanbul fork.

**Comment by shahafn** [comment]
@crossoveranx  hey, sorry for the late response. Does this still occur? If so, can you please provide the server logs? 
I'm available also at our telegram if you want to take that there.

**Comment by drortirosh** [comment]
Seems like your relay is working fine now.
Can you share what was the problem, and how it was solved?
