### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by obernardovieira** [opengsn/gsn#354]
Hi,

I'm using GSNv1 and I'm trying to move to opengsn.
I've extended my contracts as explained [here](https://docs.opengsn.org/contracts/index.html) and looked at metacoin as an example as well.
I've followed https://docs.opengsn.org/gsn-provider/getting-started.html, did every step has explained and I have the relayer running.

Then I've tried to implement the frontend, but I had an error. I removed everything and left only the import, like `const { RelayProvider } = require('@opengsn/gsn')` (on line 38) and I'm having the same error, described below.

I'm using `"@opengsn/gsn": "0.8.4"`

Can you guys help me, please?

```javascript
react-dom.development.js:11887 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (response.js:42)
    at Object../node_modules/express/lib/response.js (response.js:1142)
    at __webpack_require__ (bootstrap:790)
    at fn (bootstrap:150)
    at Object../node_modules/express/lib/express.js (express.js:22)
    at __webpack_require__ (bootstrap:790)
    at fn (bootstrap:150)
    at Object../node_modules/express/index.js (index.js:11)
    at __webpack_require__ (bootstrap:790)
    at fn (bootstrap:150)
    at Object../node_modules/@opengsn/gsn/dist/src/relayserver/HttpServer.js (HttpServer.js:1)
    at __webpack_require__ (bootstrap:790)
    at fn (bootstrap:150)
    at Object../node_modules/@opengsn/gsn/dist/src/relayclient/DevRelayClient.js (DevRelayClient.ts:3)
    at __webpack_require__ (bootstrap:790)
    at fn (bootstrap:150)
    at Object../node_modules/@opengsn/gsn/dist/src/relayclient/GsnDevProvider.js (GsnDevProvider.ts:2)
    at __webpack_require__ (bootstrap:790)
    at fn (bootstrap:150)
    at Object../node_modules/@opengsn/gsn/dist/index.js (index.js:7)
    at __webpack_require__ (bootstrap:790)
    at fn (bootstrap:150)
    at Module../src/routes/Store/Navbar.tsx (Navbar.tsx:38)
    at __webpack_require__ (bootstrap:790)
    at fn (bootstrap:150)
    at Module../src/routes/Store/index.tsx (Navbar.tsx:532)
    at __webpack_require__ (bootstrap:790)
    at fn (bootstrap:150)
```

**Comment by drortirosh** [comment]
Sorry for that. We'll get that fixed.
as an interim solution, you can do:
```javascript
import { RelayProvider } from '@opengsn/gsn/dist/src/relayclient/RelayProvider'
```

**Comment by obernardovieira** [comment]
Hi, thank you so much :pray: It indeed worked, but I have another problem now. When doing the transaction, I see

```bash
Error: Rejected relayTransaction call - should not happen. Reason: Error: Failed to sign relayed transaction for 0x2c9148e1b714fae5f31c76425445db64849ef03f
```

I have the following code
```javascript
const wallet = Wallet.createRandom(); // method from ethers.js
const { address } = wallet;
const configuration = {
    relayHubAddress: networkAddresses.development.relayHub,
    stakeManagerAddress: networkAddresses.development.stakeManager,
};
const currentProvider: any = (new Web3('http://localhost:8545')).currentProvider;
const provider = new RelayProvider(currentProvider, configuration);
const web3 = new Web3(provider);

const myRecipient = new web3.eth.Contract(
    StampetyABI as any,
    props.stampetyInstance.address,
);

// Sends the transaction via the GSN
myRecipient.methods.addStore(fullLoyaltyCard)
    .send({
        from: address,
        paymaster: networkAddresses.development.paymaster,
        forwarder: networkAddresses.development.forwarder,
    }).then(console.log)
    .catch((e: any) => {
        console.log(e); // error being printed from this line.
    });
```

**Comment by drortirosh** [comment]
RelayProvider uses the given `currentProvider` to do the actual signing.
You created a wallet (address and private-key), and used the address as `from` field - but the provider you use doesn't know how to sign using that key.
what you should use as a "from" field is an account from your currentProvider.
e.g. `(await web3.getAccounts())[1]`
You can verify that this account is used only for signing, and doesn't pay for gas, even if it has ether (e.g. by calling web3.eth.getBalance before/after your method call, and verify that it didn't use its own eth..)
If you run that test inside a web browser with metamask, you'll notice that metamask asks you for "Sign" confirmation, and not for "send transaction"

**Comment by obernardovieira** [comment]
> You created a wallet (address and private-key), and used the address as `from` field

That's exactly the goal.

I'm moving from openzeppelin-gsn to opengsn. I'm doing exactly that, create a wallet, and signing with it. And works.

The goal is to create a new wallet and sign with it. How do you recommend me to do it?

**Comment by drortirosh** [comment]
Create the new account with `const { address } = relayProvider.newAccount()`

**Comment by obernardovieira** [comment]
Oh thanks :pray: 

But now I get another error, still when sending the transaction

```
Error: Failed to relay call. Results:
Ping errors (0):Relaying errors (1):
http://localhost:8090 => Error: Got error response from relay: Returned error: VM Exception while processing transaction: revert
    at RelayProvider.ts:113
```

**Comment by drortirosh** [comment]
Hi,
Sorry for not answering earlier: we didn't notice another message on this closed issue. Please new issues for new items.

From the log portion you've sent, we're unable to tell the source of the problem. if the problem persist, please open a new issue, and give us more context as to what you're trying to do.
