### ISSUE TITLE
Using gsn in openzepplin erc20/erc721 contracts 3.x.

### ISSUE THREAD

**Issue by sanchaymittal** [opengsn/gsn#360]
The gsn documentation available at https://docs.opengsn.org/contracts/index.html, I'm using them for the new contract of erc20 and erc721. But there are couple of issues I'm facing, which includes contracts in BaseRelayRecipient are written for old solidity version. And if I upgrade them then also multiple definition of _msgSender is causing conflict too.

**Comment by drortirosh** [comment]
please check the latest 0.9.0.
we upgraded to solidity 0.6, and use the latest OpenZeppelin.

still, when you inherit both BaseRelayRecipient and OZ contract, you need to add the following method to resolve multiple-inheritance issue:

```solidity
    function _msgSender() internal override(Context, BaseRelayRecipient) view returns (address payable) {
        return BaseRelayRecipient._msgSender();
    }
```
