### ISSUE TITLE
Deprecated & Multiple documentation to enable GSN.

### ISSUE THREAD

**Issue by sanchaymittal** [opengsn/gsn#361]
There are two instances of documentation, Both of them are not working for new standards. Also it seems there are different too.

first documentation: https://docs.openzeppelin.com/contracts/3.x/gsn
second documentation: https://docs.opengsn.org/contracts/index.html

**Comment by drortirosh** [comment]
openzeppelin built their site for the old GSN.
we're in progress of writing GSNv2 and documenting it in docs.opengsn.org.

**Comment by sanchaymittal** [comment]
Ohh cool, I thought gsn is openzepplin's project.
