### ISSUE TITLE
Update to OpenZeppelin v3.0 

### ISSUE THREAD

**Issue by naszam** [opengsn/gsn#371]
Hi, 
I'm playing with opengsn contracts for a project at the HackMoney hackathon to implement a Paymaster contract.
When inheriting BasePaymaster.sol and trying to compile:
```
$ truffle compile
```
I get the following error:
```
Error: Could not find openzeppelin-solidity/contracts/access/Ownable.sol from any sources; imported from @opengsn/gsn/contracts/BasePaymaster.sol
```
I would recommend to update the contracts to OpenZeppelin v3.0.

Using the following dependences:
Ubuntu 18.04
npm v13.13.0
truffle v5.1.25
solc v0.6.7

**Comment by forshtat** [comment]
https://github.com/opengsn/gsn/pull/376
