### ISSUE TITLE
Warning: Using ".value(...)" is deprecated. Use "{value: ...}" instead.

### ISSUE THREAD

**Issue by naszam** [opengsn/gsn#372]
Hi,
I'm playing with opengsn contracts for a project at the HackMoney hackathon to implement a Paymaster contract.
When inheriting BasePaymaster.sol and trying to compile:
```
$ truffle compile
```
I get the following error:
```
    @opengsn/gsn/contracts/BasePaymaster.sol:69:9: Warning: Using ".value(...)" is deprecated. Use "{value: ...}" instead.
```
I would recommend to update to a recent solc version and update the contracts.

Using the following dependences:
Ubuntu 18.04
npm v13.13.0
truffle v5.1.25
solc v0.6.7

**Comment by forshtat** [comment]
https://github.com/opengsn/gsn/pull/376
