### ISSUE TITLE
SPDX license identifiers missing

### ISSUE THREAD

**Issue by naszam** [opengsn/gsn#375]
As of recently (Solidity 0.6.8, from this [PR](https://github.com/ethereum/solidity/pull/8907), Solidity issues warnings on all OpenGSN (and other) contracts for lack of an "[SPDX-License-Identfier](https://solidity.readthedocs.io/en/v0.6.8/layout-of-source-files.html#spdx-license-identifier)" code comment at the top of the file.

A proposed fix would be to add
```
//SPDX-License-Identifier: MIT
```
to the start of every contract file.

**Comment by forshtat** [comment]
https://github.com/opengsn/gsn/pull/376
