### ISSUE TITLE
Issue with installing dependencies 

### ISSUE THREAD

**Issue by EmanHerawy** [opengsn/gsn#488]
Hey,
Thanks for this amazing work. I am trying to learn about GSN. When I install gsn version 0.9.0, I got  `No patch files found`  in postinstall 
![image](https://user-images.githubusercontent.com/10674070/92530206-3cc13800-f22c-11ea-8721-e588878b910b.png)

gsn version : V0.9.0
Node Version :  v11.15.0
OS : Ubuntu 18

**Comment by drortirosh** [comment]
don't use 0.9 - please use the latest - 2.0.0-beta instead.
See https://github.com/opengsn/gsn/releases
for the deployed contract address on kovan, ropsten
