### ISSUE TITLE
SafeMath Import in IStakeManager.sol causes Solidity Compiler Issues

### ISSUE THREAD

**Issue by apbendi** [opengsn/gsn#501]
The `IStakeManager.sol` contract currently [imports](https://github.com/opengsn/gsn/blob/master/contracts/interfaces/IStakeManager.sol#L5) `SafeMath` from OpenZeppelin.

As far as I can tell, there is no reason for it to do this.

This import is causing compilation errors when testing our project. For more details, please read the description of [this draft PR](https://github.com/ScopeLift/umbra-protocol/pull/59). Be sure to checkout the `contracts-dev-updates` branch and navigate to the `contracts` subdirectory, then run `yarn install` and `yarn compile`.

Thanks!

**Comment by apbendi** [comment]
We resolved this issue by changing to `@openzeppelin/contracts`, since we did not need upgradeability from `@openzeppelin/contracts-ethereum-package`. However, I believe this is still an issue, and the import of SafeMath should be removed. Below are the details of the issue we were seeing:

```
Compilation errors:
contracts/Umbra.sol:11:1: DeclarationError: Identifier already declared.
import "@opengsn/gsn/contracts/interfaces/IRelayHub.sol";
^-------------------------------------------------------^
@openzeppelin/contracts-ethereum-package/contracts/math/SafeMath.sol:16:1: The previous declaration is here:
library SafeMath {
^ (Relevant source part starts here and spans across multiple lines).
```

We import SafeMath from OpenZeppelin. It is also imported via `IRelayHub.sol` via `IStakeManager.sol` by OpenGSN. As far as I can tell, this import is unneeded, however it causes a conflict with our version that prevents compilation.

Removing our SafeMath import from `Umbra.sol` does not solve the problem, because it is also imported by the OZ `SafeERC20.sol` dependency which we have.

Commenting line 5 of `IStakeManager.sol` directly in the `npm_modules` directory allows compilation. All tests pass afterwards.

**Comment by drortirosh** [comment]
thank you. 
Indeed, interfaces should not contain any unused imports.

Strangely, removing this import changes the generated bytecode of all contracts, so we probably remove it only when we make some other changes to the contracts.

Also, I don't understand why it causes a problem: 
in our code, RelayHub imports SafeMath, and later on imports IStakeManager which imports SafeMath again - without any problem.
