### ISSUE TITLE
Error running automated tests from documentation

### ISSUE THREAD

**Issue by kwedrowicz** [opengsn/gsn#530]
I downloaded example repo with automated tests (from [docs](https://docs.opengsn.org/tutorials/integration.html#automated_tests)) and tried to run them. The one checking gsn always fails with following error:
```
  1) Contract: CaptureTheFlag
       Runs with GSN:
     Error: Rejected relayTransaction call - Reason: this.remainingRelays.flatMap is not a function
      at relayClient.relayTransaction.then (node_modules/@opengsn/gsn/src/relayclient/RelayProvider.ts:136:18)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

My environment details:
OS: macOS 10.15.7
Node: v10.23.0
NPM: 6.14.8

**Comment by drortirosh** [comment]
sorry, we require node>11
(latest package adds a warning about it)

please use our forum http://forum.opengsn.org/ for questions.
