### ISSUE TITLE
Importing GSN component(RelayProviders, ConfigureGSN, etc) overrides Jest types in CRA

### ISSUE THREAD

**Issue by justussoh** [opengsn/gsn#537]
Global typing of mocha and chai imported from opengsn using `@openeth/truffle-typings` is messing with the type (in particular Assertion class) of globally inject jest causing lint and type-check to fail for `Create React Apps` applications.

**Comment by varunsrin** [comment]
+1 it looks like this is resoled in `master` now. Would be very helpful if you could drop a 2.1.1 with this fix 🙏

**Comment by drortirosh** [comment]
with the new release of 2.2.2, we've re-arranged the published packages.
you now import `@opengsn/provider`, and removed many of the temporary types, like @openeth/truffle-typings
please let us know if it works now.
