### ISSUE TITLE
Is this library production ready?

### ISSUE THREAD

**Issue by Garito** [opengsn/gsn#540]
I ask because npm audit spits a bunch of security risk mostly high

**Comment by forshtat** [comment]
Hi @Garito, and thanks for asking! Well, the GSN project consists of 3 major components: the smart contracts, the JavaScript client and the relay server. 
The smart contracts of the GSN have been audited externally and the audit report will be published in the coming days. 
The remaining code contains a relatively large number of NPM dependencies, and while we try to always use the latest versions of packages, it is not always feasible.
We will work on separating the client-side browser code and making sure it does not have any relevant known vulnerabilities in the dependency tree in the coming weeks.
Meanwhile, I would say the library is production-ready but is in fact bleeding-edge.

**Comment by Garito** [comment]
i consider this project dead, sorry
