### ISSUE TITLE
Question regarding EIP712 implementation. Is enough?  

### ISSUE THREAD

**Issue by elranu** [opengsn/gsn#598]
Hi,

I´m learning and reading the code of GSN. And I have tested the demo on https://metacoin.opengsn.org/. As far I currently understand, the `Gsn.RelayProvider`  has the responsibility to create the EIP712 message, to be signed by the user with his wallet.  In the below picture, you will see that the amount of Metacoins is `5` and the address to send the Metacoins is `0xda25d7d1bdab77deae409309b36d35ccf4295723`. On the left of the picture, you will see the EIP712 Message that is generated by the `Gsn.RelayProvider`.  On the message on Metamask, you will NOT see a property with the amount `5` and the address to transfer to ( `0xda25d7d1bdab77deae409309b36d35ccf4295723`). Also, you will NOT see the name of the method of the contract (`transfer`).  All this information is encoded in the data field. The user is not able to understand anything of the action he is signing. It has to trust on the data field. We can encode any other thing to do whatever and the user will not have any clue what is he singing. 

Don´t you think, the implementation should have an object saying the information of the contract? name of the method, and data inputs, at least? 

Probably I´m missing something,  so any explanation will help me. 

Thanks,
Mariano

![Screenshot 2021-02-18 183024](https://user-images.githubusercontent.com/873616/108434516-8cb61900-7226-11eb-8aab-304abc923ca9.png)

**Comment by garyng2000** [comment]
yes, this is a general problem even for EIP712 and the GSN is making it worse. To me, this is not much different than asking Metamask to sign a basic ethereum transaction(the opaque 0x data string), no one knows what that 'data' is about unless it goes through some RLP decoder and map to the target contract(with abi available). So at the end of the day, a 'trust me'(me being the site/app).

**Comment by drortirosh** [comment]
Indeed, GSN doesn't (and can't) solve this problem. To that extend, you might say that EIP712 "doesn't help much" with the request.
The solution is that the encoded function (`bytes[] data`) will be decoded by the wallet that displays the EIP-712 signature.
