### ISSUE TITLE
Misleading error message when paymaster contract version check fails

### ISSUE THREAD

**Issue by rjchow** [opengsn/gsn#599]
This error is thrown when the version of the paymaster contract fails the VersionManager check

```
    Provided Hub version(1.0) does not satisfy the requirement(^2.0.0)
```

It's occurring because ._validateVersion() is called on this line while resolving the paymaster contract:
https://github.com/opengsn/gsn/blob/8bd336c4b8cc47b71733bfa40e5f3a0f44c03b32/packages/common/src/ContractInteractor.ts#L184

Which results in this following line throwing the error:
https://github.com/opengsn/gsn/blob/8bd336c4b8cc47b71733bfa40e5f3a0f44c03b32/packages/common/src/ContractInteractor.ts#L217

**Comment by drortirosh** [comment]
The check is of a paymaster, so the title is misleading.
Will be fixed in next release.

**Comment by T-Damer** [comment]
Hey, anything good about solving this? I am facing same issue, our paymaster and client use same version, but it says, that the `3.0.0-beta.1 is not 3.0.0-beta.1`
