### ISSUE TITLE
BaseRelayRecipient._msgSender returns address payable

### ISSUE THREAD

**Issue by frangio** [opengsn/gsn#631]
OpenZeppelin Contracts recently changed the return type of `Context._msgSender` from `address payable` to `address`, to align with Solidity 0.8 where `msg.sender` was changed in the same way.

This is unfortunately causing our contracts to be incompatible with `BaseRelayRecipient`.

Is it possible to change `BaseRelayRecipient` and remove `payable` from the return type?

**Comment by drortirosh** [comment]
Thank you. we will do that when we upgrade our contracts to 0.8.0

Note that OpenZeppelin already have their version of BaseRelayRecipient named `ERC2771Context`, which is ABI-compatible with BaseRelayRecipient.

This means that you can already develop GSN-aware contracts on solidity 0.8.0

Unfortunately, if you need to write a paymaster, you still need opengsn base classes.
