### ISSUE TITLE
Throws error when getting transaction receipt

### ISSUE THREAD

**Issue by StillFantastic** [opengsn/gsn#649]
I'm using `ethers.js`, and when I use `wait` to get a transaction's receipt, it throws a transaction failed error even when the transaction status is success, like this one: https://ropsten.etherscan.io/tx/0x7928c57dc5c49479867593b32f3e7816d89b506d8496e94e7a3afdb9b40a7bd6.

Could it be related to how gsn provider handle receipts? Since that transaction under the hood is actually a reverted tx but is still relayed.

The gsn version I'm using is v2.2

**Comment by StillFantastic** [comment]
https://github.com/ethers-io/ethers.js/issues/564

**Comment by StillFantastic** [comment]
Found the issue, it seems like relay provider change the receipt status to 0...

**Comment by mz3944** [comment]
How did you solve/prevent this?
