### ISSUE TITLE
problem installing @opengsn/gsn@2.1.0

### ISSUE THREAD

**Issue by aster2709** [opengsn/gsn#650]
I'm looking for opengsn contracts v0.6, so I've tried ```npm i @opengsn/gsn@2.1.0``` it always gives this error.
npm: 7.15.0

----
![image](https://user-images.githubusercontent.com/39130640/120664551-a5ca9900-c4a8-11eb-835c-70af227d64ee.png)
----

Also tried installing @opengsn/contracts, but those have 0.7+ versions

**Comment by drortirosh** [comment]
Please use 2.2.0
It uses the latest deployed contracts (Solidity ver 0.7.6) and packages: please use @opengsn/provider instead of the old @opengsn/gsn
