### ISSUE TITLE
Can't penalize when the stake is unlocked

### ISSUE THREAD

**Issue by raullaprida** [opengsn/gsn#653]
When the Penalizer wants to penalize an action by calling  [relayHub.penalize()](https://github.com/opengsn/gsn/blob/176101feaf413b0a40343dbc933fb3b0cf2fc968/packages/contracts/src/Penalizer.sol#L174) , if the stake for that manager is unlocked, then the penalization [will revert](https://github.com/opengsn/gsn/blob/176101feaf413b0a40343dbc933fb3b0cf2fc968/packages/contracts/src/RelayHub.sol#L433)

As you can see [here](https://github.com/opengsn/gsn/blob/176101feaf413b0a40343dbc933fb3b0cf2fc968/packages/contracts/src/StakeManager.sol#L114), the StakeManager requires the stake to be locked

As a result, the penalization flow does not work in the following scenario:
1) A worker submits a non-compliant relay transaction (e.g, repeated nonce)
2) Having noticed that,  the owner of the stake can proceed to immediately unlock the stake
3) The Penalizer receives a penalization request (e.g, penalizeRepeatedNonce). It confirms the error so it proceeds to call relayHub.penalize
4) Since the stake was unlocked, penalize will revert

**Comment by lirazsiri** [comment]
Many thanks Raul for reporting this. We double checked and confirmed that is indeed a problem. We will be issuing a fix ASAP.  

Also, could you send an ETH address? The first proposal I'm going to suggest to governance is to create our first bug bounty :)

**Comment by shahafn** [comment]
Fixed in #659
