### ISSUE TITLE
Failed to register relay: only replay-protected (EIP-155) transactions allowed over RPC

### ISSUE THREAD

**Issue by Sulejman** [opengsn/gsn#658]
Hello, I am trying to register relay to Mumbai network using existing smart contract deployment and on relay-register, I get this message:

`Failed to register relay: only replay-protected (EIP-155) transactions allowed over RPC` 

I think I should set chainId somewhere to avoid this issue but can't figure out where.

**Comment by shahafn** [comment]
Hey @Sulejman , can you please provide more details, or exact steps to reproduce?

**Comment by aspiers** [comment]
It would be helpful to identify which transaction is failing, which code is generating it, and why it is presumably only hashing six rlp encoded elements instead of nine as per [EIP-155](https://eips.ethereum.org/EIPS/eip-155).

**Comment by drortirosh** [comment]
@Sulejman , we'd be happy to assist you, but please provide more information. 
We have a working relayer on mumbai, so its unclear for us what the problem is.
Please feel free to re-post this issue (either here, or in our Telegram, support Forum or Discord in opengsn.org)
