### ISSUE TITLE
change `getChainID` from pure to view

### ISSUE THREAD

**Issue by hack3r-0m** [opengsn/gsn#660]
https://github.com/opengsn/gsn/blob/master/packages/contracts/src/utils/GsnEip712Library.sol#L113-L118

since solidity 0.8.0 chainId retrieval should be `view` and not `pure`
reference: https://github.com/ethereum/solidity/releases/tag/v0.8.0

and if contracts are upgraded to 0.8 in the future, it is good to replace it with `block.chainid`

**Comment by drortirosh** [comment]
Yes, this is part of the changes needed when converting to 0.8 ..
