### ISSUE TITLE
Updating to OpenZeppelin v4?

### ISSUE THREAD

**Issue by superical** [opengsn/gsn#673]
It seems like the OpenZeppelin v4.x.x has moved some of their libraries into different folders. The `SafeMath` contract, for instance, has been moved from `@openzeppelin/contracts/math/SafeMath.sol` to `@openzeppelin/contracts/utils/math/SafeMath.sol`.

The `IStakeManager.sol` in `@opengsn/contracts/src/interfaces/IStakeManager.sol` imports the `SafeMath.sol` from `@openzeppelin/contracts/math/SafeMath.sol` which cannot be not found because that will only be available in the v3.4.x version of OpenZeppelin.

Will this package be updated to support v4.x.x of OpenZeppelin?

**Comment by shahafn** [comment]
Hi @superical , I actually just did that in #674

**Comment by superical** [comment]
@shahafn Awesome! Looking forward to the update! Thanks!👏
