### ISSUE TITLE
documentation: update documentation to include sample code for contracts inheriting OZ token contracts

### ISSUE THREAD

**Issue by darknightdev** [opengsn/gsn#688]
Update documentation to include the sample code showing how to integrate with contracts that are also inheriting from OpenZeppelin.Two methods _msgSender and _msgData are in conflict with oz contracts(Context.sol).Including the override methods in documentation will help save some time.

```
function _msgSender() internal override(Context, BaseRelayRecipient) view returns (address payable) {
        return BaseRelayRecipient._msgSender();
    }
function _msgData() internal override(Context, BaseRelayRecipient) view returns (bytes memory) {
        return BaseRelayRecipient._msgData();
    }
```
Currently documentation(https://docs.opengsn.org/contracts/#receiving-a-relayed-call) related to OZ contracts is bit misleading. 

Great work GSN team, this is just a minor issue that i felt might help someone integrating with GSN.

**Comment by drortirosh** [comment]
The FAQ has instructions how to do it: 
https://docs.opengsn.org/faq/troubleshooting.html#my-contract-is-using-openzeppelin-how-do-i-add-gsn-support
