### ISSUE TITLE
Any plans to release the update for solidity v0.8 and OZ4?

### ISSUE THREAD

**Issue by superical** [opengsn/gsn#689]
I understand that there has already been a PR (#673, #674) which updates GSN to support solidity v0.8 and OZ v4. The PR has already been a while.

Are there any plans on releasing a version, perhaps as a nightly or a beta, with the update so that we can start using it with the latest version of solidity and OZ? Thanks!

**Comment by drortirosh** [comment]
release 2.2.4 (released few days ago) has 0.8 support in all contracts.
