### ISSUE TITLE
Can't install @opengsn/cli due to old dependencies

### ISSUE THREAD

**Issue by CorpulentBrony** [opengsn/gsn#785]
Spent a few hours trying to get @opengsn/cli to install without any success.  I've created a brand new empty npm project and attempted just to install this package and nothing else.

It appears it may be because of a reliance on a 2 year old version of @truffle/hdwallet-provider.  When I updated this from 1.0.34 to 1.0.44, npm finishes the install with no errors.

Error log here: https://gist.github.com/CorpulentBrony/75bc28a60174cff38076c860e1c06a2a

**Comment by JasperTimm** [comment]
Same issue here, the web3 version that that version of @truffle/hdwallet-provider uses is quite old.

If anyone is looking for a fix for now, you can add an override to your `package.json`:

`"overrides": {
    "@opengsn/cli": {
      "@truffle/hdwallet-provider": "^2.0.4"
    }
  }`

**Comment by drortirosh** [comment]
calling `yarn add web3` solves the cli issue. we will fixed it in the next release.
