### ISSUE TITLE
Publish latest version of @opengsn/contracts

### ISSUE THREAD

**Issue by rahul-kothari** [opengsn/gsn#797]
@opengsn/contracts npm package v2.2.6 still uses `BaseRelayRecipient.sol`

**Comment by ihorbond** [comment]
looks like it went thru cause I got an error 
"not found @opengsn/contracts/src/BaseRelayRecipient.sol"
Is there an updated docs what to use instead ? I was reading here
https://docs.opengsn.org/contracts/#install-opengsn-contracts

**Comment by leovazquezz1** [comment]
Any updates on this?

**Comment by drortirosh** [comment]
with GSN version 3, we changed the name of the base contract to `ERC2771Recipient`, instead of `BaseRelayRecipient`
