### ISSUE TITLE
Nuxt3 + Vite + @opengsn/provider: TypeError: assert is not a function

### ISSUE THREAD

**Issue by thehedgeguy** [opengsn/gsn#804]
Hello,
I am facing an issue using Nuxt3 + Vite and @opengsn/provider

When bundling my with Browserify and importing it as a local JS script is works well,

But when making a Nuxt plugin script I get this:

```
Failed to relay call. Results:
Relaying errors (1):
http://127.0.0.1:59476 => Failed to sign relayed transaction for 0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1: TypeError: assert is not a function
```

**Comment by drortirosh** [comment]
I checked and none of the GSN packages use "assert".
I have no idea what could cause it.
