### ISSUE TITLE
how to programmatically fund paymaster by new user

### ISSUE THREAD

**Issue by mekhiya** [opengsn/gsn#815]
I am working on a project where few users fund Paymaster & many other users use gasless tx. How to allow any users to fund paymaster ? Workshop code shows WhitelistPaymaster adding trusted address & funding at deployment level. How do I make funding of paymaster dynamic by any new user?

**Comment by codev911** [comment]
just run `depositFor` function on RelayHub

**Comment by codev911** [comment]
![asfasf](https://user-images.githubusercontent.com/53482087/183365989-43fabb9b-e8e4-4000-92a1-86f3f14fa360.png)
you might run this function from your app with ethers or web3, put your `whitelistPaymaster` address and how much you want to deposit

**Comment by drortirosh** [comment]
funding paymaster is as easy as sending ETH to its address.
upon receiving those funds, it calls `relayHub.depositFor` (which means you can't see it as a balance on its address: you need to call `relayHub.balanceOf()` to tell its deposit.
