### ISSUE TITLE
Port the client library to android (Kotlin/Java)

### ISSUE THREAD

**Issue by drortirosh** [opengsn/gsn#82]
In order to support native java/kotlin app.
For Web3j, probably requires just writing a new `TransactionManager`
Roughly implements the functionality of `src/js/relayclient/RelayProvider.js` 
Please contact @drortirosh before implementing.

**Comment by divyank00** [comment]
Is this added?

**Comment by drortirosh** [comment]
no. its still a future feature. if you do want to help and implement it, we'd be happy...
(even a java wrapper to a javascript code might be good at least for some projects)
