### ISSUE TITLE
Support for Goerli Test Net

### ISSUE THREAD

**Issue by aadharshkannan** [opengsn/gsn#827]
Given that Ropsten and many other test nets are going to be deprecated. Can you please support Goerli Test Net?

**Comment by shahafn** [comment]
Hi @aadharshkannan yes we will support Goerli. In fact, gsn v3 is currently on development testing to on Goerli. In the meantime, you can use other test networks such as Kovan and Rinkeby.

**Comment by drortirosh** [comment]
GSN v3 is deployed on goerli. see https://relays.opengsn.org
