### ISSUE TITLE
CLI Deploy Error: only replay-protected (EIP-155) transactions allowed over RPC

### ISSUE THREAD

**Issue by dahof1** [opengsn/gsn#832]
Using the cli to deploy the gsn contracts (e.g. on fantom) results in an "Error: only replay-protected (EIP-155) transactions allowed over RPC"  Error.

It looks like that the used version of hdwalled-provider is too old and should be upgraded ( >= 2.x)

**Comment by drortirosh** [comment]
the `gsn deploy` script is now deprecated, and used for testing purposes only (e.g. to install on local hardhat/ganache node)
the new deployment script is using `hardhat deploy` in the `packages/deployer` folder.
