### ISSUE TITLE
solpp.js script is not working on windows

### ISSUE THREAD

**Issue by dahof1** [opengsn/gsn#834]
The helper script "solpp.js" (under scripts) will not work on windows because windows uses a different file separator ("/", "\\")

The following line will causes the trouble:
```
const dest = orig.replace(contractsFolder, outAbiFolder)
```

a quick and dirty workaround fixes the issue for me
```
const dest = orig.replace("src", "solpp")
```

**Comment by drortirosh** [comment]
Sorry. GSN **build** environment was created for Posix OS's - Linux and MacOS...
you can still create an application that uses GSN **npm packages** on windows.
