### ISSUE TITLE
Update truffle hdwallet-provider dependency in @opengsn/cli

### ISSUE THREAD

**Issue by MBRGA** [opengsn/gsn#846]
`@truffle/hdwallet-provider@1.0.34` fails to install on Node 12.22, npm 8.12.2 on Linux:
`Linux version 5.13.0-1022-azure (buildd@ubuntu) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34)`

I think it's an issue with an old version of sha3 that causes problems on newer versions of Node. I haven't worked out why installing `@opengsn/cli` itself still seems to sometimes work under npm and yarn classic (but fails under new yarn).

**Comment by red-saint-nft** [comment]
Possibly related @MBRGA? https://forum.opengsn.org/t/error-getting-right-account-with-gsn-deploy/346

**Comment by MBRGA** [comment]
Thanks for the reply @red-saint-nft , but I'm not even managing to install the package.

**Comment by drortirosh** [comment]
We've lately upgraded the project to use use the latest hdwallet-provider (2.0.11) 
please let us know if this is still an issue.
