### ISSUE TITLE
Argument of type 'RelayProvider' is not assignable to parameter of type 'ExternalProvider | JsonRpcFetchFunc'

### ISSUE THREAD

**Issue by T-Damer** [opengsn/gsn#878]
I want to wrap `RelayProvider` into `Web3Provider` from `ethers.js`, like [you did in instructions](https://docs.opengsn.org/javascript-client/getting-started.html#adding-gsn-support-to-existing-app) 
I am using: 
```JSON
    "ethers": "^5.6.9",
    "@typechain/ethers-v5": "^10.1.0",
```
Maybe there's a workaround for this? I need to call the mint function with this web3provider:
```TS
        const relayProvider = await RelayProvider.newProvider({
          provider: new WrapBridge(
            new Eip1193Bridge(provider.getSigner(), provider)
          ),
          config: {
            paymasterAddress: env.VITE_PAYMASTER_ADDRESS,
            preferredRelays: [env.VITE_GSN_SC_RELAY],
            loggerConfiguration: {
              logLevel: 'debug',
            },
          },
        }).init()

        const ethersProvider = new Web3Provider(
          relayProvider as unknown as ExternalProvider
        )
```
As you can see, right now only double conversion saves the day, but why can't I simply pass `relayProvider`? Maybe I need some kind of bridge?

**Comment by drortirosh** [comment]
Please try GSN 3.0, where we added helper `wrapProvider` and `wrapContract` exactly for this purpose: using GSN with **ethers** based contracts.

**Comment by sdelvalle57** [comment]
> Please try GSN 3.0, where we added helper `wrapProvider` and `wrapContract` exactly for this purpose: using GSN with **ethers** based contracts.

Can you please clarify more this? Cant get to find these helpers you are talking about

cheers
