### ISSUE TITLE
Using @opengsn/provider on angular got error

### ISSUE THREAD

**Issue by codev911** [opengsn/gsn#879]
hi there, i have tried @opengsn/provider with ethers and got this error, i have follow all tutorial.

**Comment by codev911** [comment]
![image](https://user-images.githubusercontent.com/53482087/183365319-a9aa83c9-ec77-41ea-ad30-0583165e6b51.png)

**Comment by drortirosh** [comment]
This is an old (2.2) version of GSN. Please try to use the latest GSN (3.0)
