### ISSUE TITLE
TokenPaymaster's getPayer function returns target address instead of initiator's address

### ISSUE THREAD

**Issue by nsharmazbyte** [opengsn/gsn#884]
It should return relayRequest.request.from;

**Comment by forshtat** [comment]
> It should return relayRequest.request.from;

I believe the `TokenPaymaster` is supposed to show how the recipient contract can pay for gas in ERC-20 token it holds using the TokenPaymaster. The `relayRequest.request.from` address will not be able to issue an allowance without paying for gas for a regular token.
The `from` is used in a `permit`-based Paymaster samples.
In any case, all paymasters in our repos are samples.
