### ISSUE TITLE
impossible to register new relay - no button (or anything else) "Register New Relay" on the site https://relays.opengsn.org/

### ISSUE THREAD

**Issue by rmlcu** [opengsn/gsn#901]
hi there

in the installation guide there is step involved to register new relay after installation:

![image](https://user-images.githubusercontent.com/102153607/189854047-69d99ab0-6a00-4180-99f4-0827b89d6dd9.png)
https://docs.opengsn.org/relay-server/tutorial.html#relayer-staking-and-registration

there is no anything that can resemble button "Register New Relay" so it's impossible to register new relay: neither v3 nor v2 (at https://relays-v2.opengsn.org/)

how to register new v3 relay?

**Comment by forshtat** [comment]
Hello @rmlcu 
I apologise for the inconvenience, the documentation was updated before the updated relays list page.

You can access the Relay Registration tool on the staging site:
https://relays-next.opengsn.org/

We will resolve the issue during the day.

**Comment by drortirosh** [comment]
Issue resolved, and https://relays.opengsn.org is now live with "Register New Relayer" button.
