### ISSUE TITLE
Running run-with-gsn errors (v3 beta)

### ISSUE THREAD

**Issue by akornato** [opengsn/gsn#906]
**Describe the bug**
Running `npx run-with-gsn 'ls'` errors with `error: unknown option '--withNode'`

**Steps To Reproduce**
1. Run `npx run-with-gsn 'ls'`

**Expected behavior**
As described at https://docs.opengsn.org/javascript-client/getting-started.html#adding-gsn-support-to-existing-app

**Console Logs and/or Screenshots**
`error: unknown option '--withNode'`

**Comment by forshtat** [comment]
Thanks, indeed `--withNode` option has been removed. Updated the documentation.
