### ISSUE TITLE
Running gsn start errors (v3 beta)

### ISSUE THREAD

**Issue by akornato** [opengsn/gsn#907]
**Describe the bug**

When `gsn start` is run against a fresh Hardhat Network, it doesn't itself log any errors.

However, looking at Hardhat logs, the following exceptions are shown (in that order):

- `relay manager not staked`
- `relayManager not found` x 2
- `relay manager not staked` x 2
- `this hub is not authorized by SM`
- `relayManager not found` x 2

I'm not yet sure if these affect the resulting GSN env.

**Steps To Reproduce**

1. `hardhat node`
2. `gsn start`

**Expected behavior**

No errors?

**Comment by forshtat** [comment]
Hi @akornato 
I believe this may be emitted to the hardhat's log when view calls are made to the node to check the state of the relay.
Please let me know if you see any transactions being sent by the Relay Server and getting reverted.
Thanks!
