### ISSUE TITLE
RelayProvider.newProvider errors on Goerli (v3 beta)

### ISSUE THREAD

**Issue by akornato** [opengsn/gsn#908]
**Describe the bug**
`RelayProvider.newProvider` throws `Error: Provided Paymaster version(3.0.0-beta.0+opengsn.test-pea.ipaymaster) does not satisfy the requirement(^3.0.0-beta.2)`.

**Steps To Reproduce**
1. Deploy your contract with forwarder address as at https://docs.opengsn.org/networks/ethereum/goerli.html
2. Configure `RelayProviderClass.newProvider` with paymaster address as at ☝️ 

Workaround: `set requiredVersionRange in your  client GSNConfig  to ^3.0.0-beta.0 so it allows you to work with the current contracts version.` (thanks to @shahafn on Discord)

**Expected behavior**
It should work.

**Comment by rslobodian** [comment]
+1, Ran into this issue today as well

**Comment by forshtat** [comment]
@akornato @rslobodian 

There has been an inconsistency between a version deployed on Goerli and published to NPM. 

Right now, both NPM and Goerli have the `3.0.0-beta.3` versions and should work properly until we break things again 😀

Apologies for the inconvenience.
