### ISSUE TITLE
RelayProvider can't be run in web worker because of dependency that tries to get window object

### ISSUE THREAD

**Issue by andyjagoe** [opengsn/gsn#909]
**Is your feature request related to a problem? Please describe.**

ClientWinstonLogger.ts has multiple references to the browser window object, but window does not exist when running in a web and the error is not caught, so result is execution halts with a ReferenceError.

**Describe the solution you'd like**
If window does not exist, the error should be caught and createClientLogger should return log, using the loglevel package and not winston. (self can be used instead of window for some capabilities, but web workers cannot access localstorage)

**Describe alternatives you've considered**
None. Are there build instructions anywhere? I was going to look at doing a fix and submitting a PR, but there are so many scripts in package.json I'm not sure what the correct build process is.

**Additional context**
I'm running RelayProvider as part of a privacy preserving analytics library I've received an ipfs dev grant for from Filecoin Foundation (https://github.com/ipfs/devgrants/issues/222). When a user visits an app instrumented with my tracker, it needs to process a RelayProvider transaction as fast as possible and also begin logging data to ipfs. If I don't run RelayProvider in a separate web worker thread, it blocks the rest of my tracking library from executing for many seconds and results in lost data for short app visits.

**Comment by forshtat** [comment]
Hi @andyjagoe 
`ClientWinstonLogger` has been removed from `@opengs/provider` package and should not be required any more. 
Please tell us if you still have this issue with version `3.0.0-beta.3`.
