### ISSUE TITLE
Switch from Web3 to Ethers

### ISSUE THREAD

**Issue by andyjagoe** [opengsn/gsn#910]
**Is your feature request related to a problem? Please describe.**
RelayProvider is my projects only dependency on web3.js and alone adds 1.4MB of size to my package and much slower performance than if it could run with ethers. 

**Describe the solution you'd like**
Provide an option for RelayProvider to use ethers on the back-end instead of using Web3.

**Describe alternatives you've considered**
There's a new project called https://github.com/dawsbot/essential-eth that is twice as fast as ethers and even smaller in size that might be worth watching. It only handles read functions currently, but I believe will have write functions in the future.

**Additional context**
I'm running RelayProvider as part of a privacy preserving analytics library I've received an ipfs dev grant for from Filecoin Foundation (https://github.com/ipfs/devgrants/issues/222). When a user visits an app instrumented with my tracker, it needs to process a RelayProvider transaction as fast as possible and also begin logging data to ipfs. Size of package and speed of libraries are very important to performance of the solution which needs to run as fast as possible on page loading.

**Comment by harbu** [comment]
Hello there!

We are encountering a similar situation where the size of our webpack bundle is growing by about 2MB, apparently due to the inclusion of `web3` and `@ethereumjs` packages. Wondering if you ever found a way to get around the issue? Upgrading from v2 to v3 could help?

Sincerely, -Eric from Streamr

**Comment by andyjagoe** [comment]
Unfortunately not. Upgrading to v3 allows you to remove the dependency for `web3` in your code, but `opengsn` still has a dependency on `web3` itself so it doesn't help with package size. The only way that might address the situation I'm aware of is to refactor `opengsn` to use ethers instead of `web3` though haven't looked to see if everything `opengsn` needs to operate is available in `ethers`. @drortirosh would probably know.

**Comment by harbu** [comment]
Thanks for the answer

**Comment by louis-md** [comment]
💯 Fully agree, we worked hard to divide by 2 the bundle size of our dapp by removing completely our dependency to web3js. Sad to see it has to come back in our project just because we want to use GSN.

I'd be happy to help refactoring the project if that's ever decided. Winding up this integration is now my #1 priority.

Thanks for the amazing job anyways 💪

**Comment by forshtat** [comment]
@andyjagoe @harbu @louis-md 

The first build with Ethers.js as an underlying library is merged and published as `3.0.0-beta.5`.

**Comment by louis-md** [comment]
Hey @forshtat 

Thanks a lot for all the work!

The bundle size has considerably reduced, congrats 💪

I  was wondering if it could be considered to also remove the  dependency to `abi-decoder`, at least from @opengsn/provider, as it still imports web3-utils and web3-eth-abi, which costs about 1.4mb for almost nothing.

That would remove for good any remaining dependency to web3 if I'm correct.

<img width="1680" alt="Capture d’écran 2023-03-16 à 20 53 53" src="https://user-images.githubusercontent.com/8128346/225738083-04b987ea-8ba9-434f-8db8-2a03ee79e424.png">

**Comment by forshtat** [comment]
Hi @louis-md 
How can I generate these diagrams?

I checked the bundle size with ["source-map-explorer"](https://github.com/danvk/source-map-explorer) and it did not appear that it imports 1.4 MB for `abi-decoder`. The `web3-utils` is 54.57 kb and `web-eth-abi` is 4.29 kb, am I missing something?

<img width="1355" alt="Screenshot 2023-03-16 at 22 29 58" src="https://user-images.githubusercontent.com/40541447/225746595-b22fcc78-d674-45f6-a7e5-8517e5070e62.png">

**Comment by louis-md** [comment]
I used [`@next/bundle-analyzer`](https://www.npmjs.com/package/@next/bundle-analyzer) to create the diagram.

Yes you are right, these packages are tiny. Dependency to web3js actually came from another dependency. I managed to remove it 👍
