### ISSUE TITLE
gsn helpers page outdated

### ISSUE THREAD

**Issue by akornato** [opengsn/gsn#913]
https://docs.opengsn.org/javascript-client/gsn-helpers.html#deploy

There's no `--save-dev` for `yarn`, instead there's `--dev`

https://docs.opengsn.org/javascript-client/gsn-helpers.html#start

`Property 'loadDeployments' does not exist on type 'GsnTestEnvironmentClass'. Did you mean 'loadDeployment'?`

**Comment by forshtat** [comment]
Thanks, @akornato ! Pushed the fixes to the docs.
