### ISSUE TITLE
exec /usr/local/bin/docker-entrypoint.sh: exec format error

### ISSUE THREAD

**Issue by ChromMob** [opengsn/gsn#915]
**Describe the bug**
Getting exec /usr/local/bin/docker-entrypoint.sh: exec format error when running docker-compose up on arm64 machine.

**Steps To Reproduce**
1. Do everything according to this guide: [https://docs.opengsn.org/relay-server/tutorial.htm]
2. Reach the point where you run docker-compose up
3. Run docker-compose up
4. Get an error

**Expected behavior**
The server running 🤣 

**Console Logs and/or Screenshots**
[log.txt](https://github.com/opengsn/gsn/files/9964372/log.txt)

**Comment by forshtat** [comment]
The entire tech stack of OpenGSN is node.js and javascript-based and should not have any issues with arm64 or any other platform. Closing for now as nobody seems to have had this issue since then. Please open a new one if you still encounter such error.
