### ISSUE TITLE
Unacceptable relayMaxNonce: 874. current nonce 875 error

### ISSUE THREAD

**Issue by jogamod** [opengsn/gsn#948]
**Describe the bug**
I am unable to send more than 4 transactions at a time (per second), but for my airdrop, this should be a much higher number.
If I sent more than 4, let's say 10, the 4 of them will be executed while the 6 of them will be reverted with the following error message:
`Got error response from relay: Unacceptable relayMaxNonce: 874. current nonce 875`

**Steps To Reproduce**
_No actual steps to reproduce_

**Expected behavior**
To have a much higher throughput with the transactions, or at least to have some kind of a queue where transactions could be sent and not get reverted.

**Console Logs and/or Screenshots**
![image](https://user-images.githubusercontent.com/22684418/223728535-b5fdedc4-d9f0-42c2-bd8d-e3be6e8fe792.png)

** Link to your project's repository **
_Not open source_

**Additional context**
docker image version is `opengsn/jsrelay:2.2.3`

I hope someone could take a look and help me with this. Thanks in advance!

**Comment by forshtat** [comment]
Hi @jogamod 
The number of transactions client will send to the same relay without waiting for them to be
